# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(System.DefaultWorkingDirectory)'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'
    


- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(2a4154cb-de55-44f4-b490-8ec1668a19e4)'
    appType: 'webApp'
    appName: 'IODPDatamineApp'
    deployToSlotOrASE: true
    resourceGroupName: 'vptest-rg-dev'
    slotName: 'staging'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Azure subscription 1(2a4154cb-de55-44f4-b490-8ec1668a19e4)'
    Action: 'Swap Slots'
    WebAppName: 'IODPDatamineApp'
    ResourceGroupName: 'vptest-rg-dev'
    SourceSlot: 'staging'